### ISSUE TITLE
Dependency on old debugger.  Won't work with 1.2.0

### ISSUE THREAD

**Issue by noctivityinc** [nixme/pry-debugger#17]
I get this when adding `gem pry-debugger` to my gemfile.

```
 In Gemfile:
   pry-debugger (>= 0) ruby depends on
     debugger (~> 1.1.3) ruby

   debugger (1.2.0)
```

**Comment by shlomif** [comment]
I ran into this problem as well when packaging pry-debugger for Mageia Linux 3. Please fix it.

**Comment by stevenharman** [comment]
Any plans for a new release so we can get around this?

**Comment by nixme** [comment]
New version 0.2.1 released.
