### ISSUE TITLE
Ruby 2.0 dependencies

### ISSUE THREAD

**Issue by avit** [nixme/pry-debugger#23]
debugger-ruby_core_source 1.2.0 was released for compatibility with ruby-2.0.0-p0.

pry-debugger currently depends on debugger-ruby_core_source (~> 1.1.2)

**Comment by banister** [comment]
But debugger itself doesn't work on 2.0 yet right?

**Comment by avit** [comment]
Maybe right... you would know better. Guess we have to wait.

**Comment by nixme** [comment]
debugger has some issues with 2.0 right now, e.g. `step_over` messes up when a `method_missing` is involved. But  I've relaxed the dependency on debugger so new pry-debugger's don't need to be released to keep up.

**Comment by tessi** [comment]
Here is a debugger fork that claims to work with 2.0 https://github.com/ko1/debugger2
