### ISSUE TITLE
jruby 1.7.2 cannot install pry-debugger gem

### ISSUE THREAD

**Issue by ghost** [nixme/pry-debugger#26]
using jruby 1.7.2
running on ubuntu 12.04 64bit.
# jruby -S gem install pry-debugger

Building native extensions.  This could take a while...
ERROR:  Error installing pry-debugger:
    ERROR: Failed to build gem native extension.

```
    /opt/jruby-1.7.2/bin/jruby extconf.rb
```

NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.

   (root) at /opt/jruby-1.7.2/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1027
   (root) at /opt/jruby-1.7.2/lib/ruby/shared/rubygems/custom_require.rb:1
   (root) at extconf.rb:1

Gem files will remain installed in /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/debugger-linecache-1.1.2 for inspection.
Results logged to /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/debugger-linecache-1.1.2/ext/trace_nums/gem_make.out
16:16:38:(2),jobs=0,cmd#=2,hist#=1081
root@wt-lanai[~]
# cat /opt/jruby-1.7.2/lib/ruby/gems/shared/gems/debugger-linecache-1.1.2/ext/trace_nums/gem_make.out

/opt/jruby-1.7.2/bin/jruby extconf.rb
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.

   (root) at /opt/jruby-1.7.2/lib/ruby/shared/mkmf.rb:8
  require at org/jruby/RubyKernel.java:1027
   (root) at /opt/jruby-1.7.2/lib/ruby/shared/rubygems/custom_require.rb:1
   (root) at extconf.rb:1

**Comment by banister** [comment]
The README states only MRI is supported, i'm not sure when we'll be able to support jruby
