### ISSUE TITLE
Failed compiling for Ruby2.0.0p0 x64 under windows 

### ISSUE THREAD

**Issue by Crossverse** [nixme/pry-debugger#29]
C:\Legacy\Ruby200-x64\bin>gem install pry-debugger
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing pry-debugger:
    ERROR: Failed to build gem native extension.

```
C:/Legacy/Ruby200-x64/bin/ruby.exe extconf.rb
```

checking for rb_method_entry_t.called_id in method.h... no
checking for rb_control_frame_t.method_id in method.h... no
checking for rb_method_entry_t.called_id in method.h... no
checking for rb_control_frame_t.method_id in method.h... no
checking for rb_method_entry_t.called_id in method.h... yes
checking for vm_core.h... yes
checking for iseq.h... yes
checking for insns.inc... yes
checking for insns_info.inc... yes
checking for eval_intern.h... yes
checking for struct iseq_line_info_entry in vm_core.h,iseq.h... yes
checking for if rb_iseq_compile_with_option was added an argument filepath... yes
creating Makefile

make
generating ruby_debug-x64-mingw32.def
compiling breakpoint.c
compiling ruby_debug.c
ruby_debug.c:27:19: error: conflicting types for 'rb_iseq_compile_with_option'
In file included from ruby_debug.c:4:0:
C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-ruby_core_source-1.2.0/lib/debugger/ruby_core_source/ruby-2.0.0-p0/vm_core.h:646:7: note: previous declaration of 'rb_iseq_compile_with_option' was here
ruby_debug.c: In function 'save_call_frame':
ruby_debug.c:493:31: warning: operation on 'debug_context->frames' may be undefined [-Wsequence-point]
ruby_debug.c:506:53: error: 'rb_control_frame_t' has no member named 'bp'
ruby_debug.c: In function 'set_thread_event_flag_i':
ruby_debug.c:698:7: error: 'rb_thread_t' has no member named 'event_flags'
ruby_debug.c:698:24: error: 'RUBY_EVENT_VM' undeclared (first use in this function)
ruby_debug.c:698:24: note: each undeclared identifier is reported only once for each function it appears in
ruby_debug.c: In function 'debug_event_hook':
ruby_debug.c:727:16: error: 'ID_ALLOCATOR' undeclared (first use in this function)
ruby_debug.c:780:96: error: 'rb_control_frame_t' has no member named 'bp'
ruby_debug.c:952:102: error: 'rb_control_frame_t' has no member named 'bp'
ruby_debug.c: In function 'context_frame_id':
ruby_debug.c:1756:8: warning: unused variable 'id' [-Wunused-variable]
ruby_debug.c: In function 'context_frame_file':
ruby_debug.c:1823:45: error: 'rb_iseq_t' has no member named 'filename'
ruby_debug.c: In function 'copy_scalar_args':
ruby_debug.c:1861:24: error: 'rb_control_frame_t' has no member named 'dfp'
ruby_debug.c: In function 'context_copy_locals':
ruby_debug.c:1922:46: error: 'rb_control_frame_t' has no member named 'dfp'
ruby_debug.c:1940:62: error: 'rb_control_frame_t' has no member named 'dfp'
ruby_debug.c: In function 'context_jump':
ruby_debug.c:2407:63: error: 'rb_iseq_t' has no member named 'filename'
ruby_debug.c:2409:38: error: 'rb_iseq_t' has no member named 'insn_info_size'
ruby_debug.c:2411:30: error: 'rb_iseq_t' has no member named 'insn_info_table'
ruby_debug.c:2422:56: error: 'rb_iseq_t' has no member named 'insn_info_table'
In file included from ruby_debug.c:9:0:
ruby_debug.c: At top level:
C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-ruby_core_source-1.2.0/lib/debugger/ruby_core_source/ruby-2.0.0-p0/insns_info.inc:695:1: warning: 'insn_name' defined but not used [-Wunused-function]
C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-ruby_core_source-1.2.0/lib/debugger/ruby_core_source/ruby-2.0.0-p0/insns_info.inc:701:1: warning: 'insn_op_types' defined but not used [-Wunused-function]
C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-ruby_core_source-1.2.0/lib/debugger/ruby_core_source/ruby-2.0.0-p0/insns_info.inc:707:1: warning: 'insn_op_type' defined but not used [-Wunused-function]
ruby_debug.c: In function 'context_frame_file':
ruby_debug.c:1824:1: warning: control reaches end of non-void function [-Wreturn-type]
make: **\* [ruby_debug.o] Error 1

Gem files will remain installed in C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-1.2.4 for inspection.
Results logged to C:/Legacy/Ruby200-x64/lib/ruby/gems/2.0.0/gems/debugger-1.2.4/ext/ruby_debug/gem_make.out

**Comment by banister** [comment]
Surely you can see this is an UPSTREAM problem in the `debugger` gem itself, it doesn't yet have 2.0 support.

**Comment by Crossverse** [comment]
now debugger have ruby 2.0 support but pry-debugger not compiled anyway.

**Comment by Crossverse** [comment]
please reopen issue

**Comment by kyrylo** [comment]
@Crossverse, https://github.com/cldwalker/debugger/commit/e98dc5762a48ea280fe7b8de4325175076167fbc
