### ISSUE TITLE
Feature Request: Need a  Way to Try Next  Line

### ISSUE THREAD

**Issue by jackdesert** [nixme/pry-debugger#30]
When I'm halted at a breakpoint, right before the line where I suspect my code may throw an exception, I OFTEN find myself leaving the   keyboard to copy the next line with the mouse, paste it in, and hit "Enter"

The goal of this is to try the next line of code without being forced out of Ruby if the line throws an exception. The capability is already there via cut and paste. But what would really make Pry a KILLER APP for me is if there were a command like 

  try-next

That does exactly that for me--runs the next line of code wiithout forcing me out of Ruby if it breaks.

**Comment by banister** [comment]
Pry already has this feature, it's called `play`, type: `play -l LINE_NUMBER` to play that line, This is a feature in pry independent of `pry-debugger`

see here: http://showterm.io/eef3ea97603a3f5b5a555

Type `play -h` inside pry for more information (dont check the wiki as i think it's out of date)

**Comment by banister** [comment]
I forgot to ask, is this solution ok? :)

**Comment by jackdesert** [comment]
Yes, that works and is much easier than copying and pasting a line. 

I would still like a shortcut to play the current line. Is there an easy way to get that?
