### ISSUE TITLE
debugger not work

### ISSUE THREAD

**Issue by artofhuman** [nixme/pry-debugger#39]
breakpoint stop and not show code and methods not avaliable 

[5] pry(CompanyDeleter)> ls
NoMethodError: undefined method `term' for ["ls", :ident]:CodeRay::Tokens
from /home/semen/.rvm/gems/ruby-1.9.3-p429@pulscen/gems/coderay-1.0.8/lib/coderay/tokens.rb:83:in`rescue in method_missing'

**Comment by nixme** [comment]
Can you give me some more information about which exact versions of gems, ruby, etc. that you're running?

**Comment by artofhuman** [comment]
Ruby 1.9.3p429 (2013-05-15 revision 40747) [x86_64-linux]

Using pry (0.9.10) 
Using pry-debugger (0.2.2) 
Using pry-rails (0.2.2) 
Using pry-stack_explorer (0.4.7)

**Comment by artofhuman** [comment]
I find that problem in spec

**Comment by artofhuman** [comment]
Problem is solved.
