### ISSUE TITLE
next working as step

### ISSUE THREAD

**Issue by AHaymond** [nixme/pry-debugger#47]
I have installed pry-debugger with pry-rails. When using binding.pry, the `next` command is working as the `step` command. I am using pry version 0.9.12.6 and pry-debugger 0.2.2

**Comment by nixme** [comment]
Dupe of #34. Please use `pry-byebug` for now.

**Comment by AHaymond** [comment]
I just discovered pry-byebug as a workaround. Thanks for the tip anyhow.
