### ISSUE TITLE
next does not work (windows)

### ISSUE THREAD

**Issue by dhawal55** [nixme/pry-debugger#50]
next command is supposed to step to the next line. However, I have had several instances where it just continues execution and does not stop at the next line. I'm running this on a windows box so this could be specific to windows.

**Comment by shoe** [comment]
Possibly not specific to windows.  I see this behavior on Linux.

**Comment by markburns** [comment]
same on OSX

**Comment by markburns** [comment]
maybe a dupe of https://github.com/nixme/pry-debugger/issues/34 pry-byebug solves this issue for me

**Comment by nixme** [comment]
Yes. Duplicate of #34. Please use `pry-byebug` in the meantime.
