### ISSUE TITLE
Release a patch version that works with Pry v0.10

### ISSUE THREAD

**Issue by teohm** [nixme/pry-debugger#54]
Hi there!

Pry v0.10 has been released for a while, and there is already a patch that allows `pry-debugger` to run together with Pry v0.10, see: https://github.com/nixme/pry-debugger/commit/c3abfc4d2c90b04bfa8513d3ec6f0c00dc599004

Is it possible to release a patch version (0.2.3), so that we all can upgrade to Pry v0.10?

**Comment by tamouse** [comment]
:+1:

**Comment by fawaf** [comment]
+1

**Comment by nixme** [comment]
0.2.3 released.

If you're using an MRI version greater than 2, you should however switch to `pry-byebug`
