### ISSUE TITLE
Confusing behavior of `n`, terminating a Rails console

### ISSUE THREAD

**Issue by dblock** [nixme/pry-debugger#55]
```
source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails'
gem 'sqlite3'

group :development, :test do
  gem 'pry-debugger'
end
```

```
$ rails c
Loading development environment (Rails 4.1.4)
2.0.0-p353 :001 > n
/tmp/n-wat$ 
```

This deserved an animated GIF.

![rails-c](https://cloud.githubusercontent.com/assets/542335/3499032/8c225826-05fb-11e4-8cb8-4f1c87079c74.gif)

It's either confusing or a bug?

**Comment by dblock** [comment]
Note that someone on Twitter reports that this doesn't happen on Linux, but only on OSX, https://twitter.com/dblockdotorg/status/486173639155261442, I don't have a Linux box to test.

**Comment by banister** [comment]
Pry has detected there's no ruby frames to step through so it's started stepping through the calling program (the shell in this case). If you continue to type 'step' you'll eventually end up stepping through Kernel code.

**Comment by dblock** [comment]
Well, no. This terminates the app without saying anything (you cannot continue typing step :). So unlikely desired behavior.

**Comment by banister** [comment]
It was a joke :)

Honestly though, what would you expect 'n' to do here? I can't think of meaningful behaviour for it in the rails console.

**Comment by jordanstephens** [comment]
@dblock Let me take back to suggestion that the behavior was different on Linux vs OS X. That statement was made before I knew it was related to pry.

The behavior is indeed the same on both platforms.

**Comment by dblock** [comment]
@banister Gotcha. My Russian sense of humor is a bit dry. I use dry-debugger for that. Oh that's bad.

@jordanstephens Cool, thanks.

I think `n` should do what `n` does in all the other cases:

```
2.0.0-p353 :001 > n
NameError: undefined local variable or method `n' for main:Object
    from (irb):1
    from /Users/dblock/.rvm/rubies/ruby-2.0.0-p353/bin/irb:12:in `<main>'
```

The really confusing thing is that I am not debugging anything! I didn't do `Binding.pry` or something else, so why is this even enabled?

**Comment by banister** [comment]
@dblock then you need to disable the aliases for next/step, they should be undefined by default so you probably have them in your.Pryrc. 

Next and step can still be useful in rails console. Imagine you typed `break` first to debug a method call in the console.

**Comment by dblock** [comment]
Nope, I don't have a .pryrc.

**Comment by banister** [comment]
@dblock then you must have a truly ancient version of Pry-debugger as the n/s aliases were removed ages ago

**Comment by dblock** [comment]
I have 0.2.3, which is the latest.

**Comment by banister** [comment]
@dblock then you must have another plugin installed which defines those shortcut commands i think. Maybe pry-nav?

**Comment by dblock** [comment]
Doesn't look like it, but I do see other weird stuff:

```
2.0.0-p353 :001 > require 'pry-debugger'
WARN: Unresolved specs during Gem::Specification.reset:
      debugger (~> 1.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Gem::LoadError: Unable to activate pry-nav-0.2.3, because pry-0.10.0 conflicts with pry (~> 0.9.10)

> n # terminates
```

**Comment by dblock** [comment]
@banister, what do you see when you do jut the above? (`irb`, `require 'pry-debugger'` and `n`)?

**Comment by banister** [comment]
Can you paste the output of `show-source n`

**Comment by dblock** [comment]
You mean in `pry`?

```
[2] pry(main)> show-source n

From: /Users/dblock/.rvm/gems/ruby-2.0.0-p353/gems/pry-0.10.0/lib/pry/command_set.rb 
Number of lines: 3

c = block_command match, desc, options do |*args|
  run action, *args
end
```

However, this happens in irb. I uninstalled pry-nav that cased that warning, fyi, same issue with `n`.

**Comment by dblock** [comment]
Also

```
2.0.0-p353 :003 > Pry::VERSION
 => "0.10.0" 
2.0.0-p353 :006 > PryDebugger::VERSION
 => "0.2.3" 
```

**Comment by banister** [comment]
You sure you don't have Pry-byebug installed?

**Comment by dblock** [comment]
```
/tmp/t$ gem uninstall pry-byebug
Successfully uninstalled pry-byebug-1.3.3
/tmp/t$ irb
2.0.0-p353 :001 > require 'pry-debugger'
WARN: Unresolved specs during Gem::Specification.reset:
      debugger (~> 1.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
 => true 
2.0.0-p353 :002 > n
```

**Comment by banister** [comment]
Those are different bugs, we were looking at the rails console quitting when you type 'n'. Could you retry that now byebug is Uninstalled?

**Comment by dblock** [comment]
I meant to say that under Rails it's the same:

```
/tmp/n-wat$ rails c
Loading development environment (Rails 4.1.4)
2.0.0-p353 :001 > n
/tmp/n-wat$ 
```

**Comment by dblock** [comment]
via @ilyakava

```
2.0.0-p353 :003 > p self.method(:n)
#<Method: Object(IRB::ExtendCommandBundle)#n>
 => #<Method: Object(IRB::ExtendCommandBundle)#n> 
2.0.0-p353 :004 > p self.method(:n).source_location
["/Users/dblock/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/irb/extend-command.rb", 172]
 => ["/Users/dblock/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/irb/extend-command.rb", 172] 
```

**Comment by banister** [comment]
So it's an irb method, not a debugger command?!

**Comment by dblock** [comment]
Honestly I have no idea. But it doesn't happen without `pry-debugger`.

**Comment by banister** [comment]
@dblock After you've uninstalled `pry-byebug` and you re-run rails console, can you please show me the output of `show-source n` again. 

If you have really uninstalled `pry-byebug` _and_ the `show-source` shows the same as before, then something extremely weird is going on and i can tell you how to monkeypatch pry itself to provide more information on where the `n` is coming from.

**Comment by dblock** [comment]
I don't get `show-source`:

```
2.0.0-p353 :002 > show-source
NameError: undefined local variable or method `show' for main:Object
```

**Comment by banister** [comment]
that means you're not in Pry, you're in irb.................................

**Comment by dblock** [comment]
Alright, so:

```
2.0.0-p353 :001 > p self.method(:n)
#<Method: Object(IRB::ExtendCommandBundle)#n>
 => #<Method: Object(IRB::ExtendCommandBundle)#n> 
2.0.0-p353 :002 > p self.method(:n).source_location
["/Users/dblock/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/irb/extend-command.rb", 172]
 => ["/Users/dblock/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/irb/extend-command.rb", 172] 
```

Monkey patched extend-command and got a caller location, `n` is defined via `ExtendCommandBundle.def_extend_command "n", :Next` in https://github.com/cldwalker/debugger/blob/master/lib/ruby-debug/commands/irb.rb#L22 and is implemented as 

``` ruby
    class Next # :nodoc:
      def self.execute(conf)
        throw :IRB_EXIT, :next
      end
    end
```

I really don't understand the purpose of all of this.

**Comment by dblock** [comment]
LMK if you want me to reopen this in the debugger gem.

**Comment by banister** [comment]
Yeah, this is an issue related to debugger, nothing to do with pry-debugger or even pry :)

**Comment by dblock** [comment]
I opened https://github.com/cldwalker/debugger/issues/133, thanks for your patience, I should have narrowed down where it was coming from further, first.
