### ISSUE TITLE
`continue` command exits Pry session

### ISSUE THREAD

**Issue by hahuang65** [nixme/pry-debugger#9]
Is there a specific reason for this? When I have multiple `binding.remote_pry` lines set, it's pretty annoying to have to `c` out of them, and start up `pry-remote` again just to get to the next debug point.

**Comment by nixme** [comment]
Hmmm.... I see what you're saying. I could keep the remote session up and running, but when should it be closed? When the app exits?

**Comment by hahuang65** [comment]
I think it should be closed when you call `exit`. And it should close when there are no more `binding.remote_pry`. I see this as the same paradigm as the regular non-remote debugger.

**Comment by snoblenet** [comment]
I am having a similar problem when calling next. I expect it to jump to the line of my code (just as I'd expect continue to take you to the next breakpoint). Instead it exits. In both cases I think we're looking for behaviour that mirrors what we've grown used to with ruby-debug.

**Comment by nixme** [comment]
If it's exiting when calling `next` that's a different issue. `continue` is resume execution of the program. `next` is only supposed to take you to the next line. It will either stop at the next line or at any breakpoint triggered between the two lines.

Can you provide more details (execution environment, example file, etc.) and file a separate bug?

**Comment by hahuang65** [comment]
I no longer care about this issue, and sorry I didn't follow up on this earlier.
